// Curated surf spots with a LOCAL KNOWLEDGE layer, ordered roughly North → South.
// `facing` = compass bearing (deg) the beach is open to the ocean (where swell comes from).
// Offshore (clean) wind blows FROM ~ facing+180. Onshore (messy) wind blows FROM ~ facing.
// `idealSwellDir` = swell direction (deg, where it comes from) the break likes best.
// `idealSize` = [min, max] wave face (ft): starts working → maxes out before it's a mess.
// `idealTide` = low | mid | high | any.
// `level` = beginner | intermediate | advanced.  `type` = beach | point | reef.

const SPOTS = [
  // ───────────── North Coast ─────────────
  { id: "trinidad", name: "Trinidad State Beach", region: "Humboldt, CA", lat: 41.059, lon: -124.147,
    facing: 270, idealSwellDir: 290, idealSize: [3, 12], idealTide: "mid", level: "advanced", type: "beach",
    note: "Cold, remote NorCal beach break wide open to heavy NW swell. Powerful and uncrowded." },

  // ───────────── SF Bay Area / San Mateo ─────────────
  { id: "bolinas", name: "Bolinas", region: "Marin County, CA", lat: 37.909, lon: -122.686,
    facing: 230, idealSwellDir: 270, idealSize: [1, 6], idealTide: "mid", level: "beginner", type: "beach",
    note: "Mellow, sheltered Marin beach break — a friendly NorCal longboard and learner spot." },
  { id: "ocean-beach-sf", name: "Ocean Beach (SF)", region: "San Francisco, CA", lat: 37.759, lon: -122.511,
    facing: 270, idealSwellDir: 270, idealSize: [3, 12], idealTide: "mid", level: "advanced", type: "beach",
    note: "Heavy, shifty beach break with serious paddle-outs and current. Punishing when big. E wind is offshore." },
  { id: "pacifica-linda-mar", name: "Linda Mar (Pacifica)", region: "Pacifica, CA", lat: 37.591, lon: -122.508,
    facing: 270, idealSwellDir: 290, idealSize: [2, 8], idealTide: "mid", level: "beginner", type: "beach",
    note: "Forgiving Bay Area beach break — the region's classic learner wave, with rentals on the sand." },
  { id: "mavericks", name: "Mavericks", region: "Half Moon Bay, CA", lat: 37.495, lon: -122.500,
    facing: 290, idealSwellDir: 300, idealSize: [8, 40], idealTide: "mid", level: "advanced", type: "reef",
    note: "Legendary big-wave reef. Cold, sharky and deadly — tow/charger territory only when it's on." },

  // ───────────── Santa Cruz / Monterey ─────────────
  { id: "steamer-lane", name: "Steamer Lane", region: "Santa Cruz, CA", lat: 36.951, lon: -122.026,
    facing: 220, idealSwellDir: 250, idealSize: [2, 12], idealTide: "mid", level: "advanced", type: "point",
    note: "Iconic performance point/reef. Handles size and crowds; rewards a clean W/NW swell." },
  { id: "pleasure-point", name: "Pleasure Point", region: "Santa Cruz, CA", lat: 36.956, lon: -121.973,
    facing: 200, idealSwellDir: 200, idealSize: [2, 8], idealTide: "low", level: "intermediate", type: "point",
    note: "Long right-hand point. Loves a mid-period W/SW swell on a medium-to-low tide. NW wind goes offshore." },
  { id: "the-hook", name: "The Hook", region: "Santa Cruz, CA", lat: 36.957, lon: -121.965,
    facing: 200, idealSwellDir: 200, idealSize: [2, 8], idealTide: "low", level: "intermediate", type: "reef",
    note: "Short, fun right reef on the east side. Best on a SW swell at lower tides; heavily localized." },
  { id: "cowells", name: "Cowell's", region: "Santa Cruz, CA", lat: 36.961, lon: -122.022,
    facing: 180, idealSwellDir: 200, idealSize: [1, 4], idealTide: "mid", level: "beginner", type: "point",
    note: "The classic learner wave. Soft, slow, forgiving rights. Best small — over 5ft it walls up and crowds." },
  { id: "carmel", name: "Carmel Beach", region: "Carmel, CA", lat: 36.554, lon: -121.927,
    facing: 250, idealSwellDir: 280, idealSize: [2, 8], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Scenic white-sand beach break that soaks up NW swell; can get punchy and shifty." },

  // ───────────── Big Sur ─────────────
  { id: "sand-dollar", name: "Sand Dollar Beach", region: "Big Sur, CA", lat: 35.922, lon: -121.466,
    facing: 250, idealSwellDir: 280, idealSize: [2, 8], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Remote Big Sur cove that catches NW swell. Isolated, cold and rarely crowded." },

  // ───────────── Central Coast (SLO County) ─────────────
  { id: "cambria-moonstone", name: "Moonstone Beach", region: "Cambria, CA", lat: 35.566, lon: -121.115,
    facing: 265, idealSwellDir: 285, idealSize: [2, 8], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Cambria beach break exposed to NW swell. Often windy and cool; pretty boardwalk setting." },
  { id: "cayucos", name: "Cayucos Pier", region: "Cayucos, CA", lat: 35.443, lon: -120.903,
    facing: 290, idealSwellDir: 290, idealSize: [2, 6], idealTide: "mid", level: "beginner", type: "beach",
    note: "Friendly longboard wave tucked by the pier. Sheltered and forgiving — best on a clean NW swell." },
  { id: "morro-rock", name: "Morro Rock", region: "Morro Bay, CA", lat: 35.372, lon: -120.866,
    facing: 275, idealSwellDir: 290, idealSize: [3, 10], idealTide: "mid", level: "advanced", type: "beach",
    note: "Powerful beach break north of the Rock. Soaks up NW swell and gets big, heavy and current-ridden." },
  { id: "montana-de-oro", name: "Montaña de Oro (Hazard)", region: "Los Osos, CA", lat: 35.288, lon: -120.886,
    facing: 270, idealSwellDir: 290, idealSize: [3, 10], idealTide: "low", level: "advanced", type: "reef",
    note: "Isolated, cold, sharky reef in the state park. Heavy on a solid NW swell — experts and low tide only." },
  { id: "shell-pirates", name: "Shell Beach / Pirates Cove", region: "Shell Beach, CA", lat: 35.176, lon: -120.714,
    facing: 215, idealSwellDir: 205, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "reef",
    note: "Sheltered reef nooks that come alive on a S/SW swell. Cleaner here when NW wind ruins everything else." },
  { id: "avila", name: "Avila Beach", region: "Avila Beach, CA", lat: 35.179, lon: -120.733,
    facing: 160, idealSwellDir: 200, idealSize: [1, 4], idealTide: "mid", level: "beginner", type: "beach",
    note: "Super protected south-facing cove. Usually calm — only really breaks when a big south swell wraps in." },
  { id: "pismo-pier", name: "Pismo Beach Pier", region: "Pismo Beach, CA", lat: 35.138, lon: -120.645,
    facing: 250, idealSwellDir: 270, idealSize: [2, 6], idealTide: "mid", level: "beginner", type: "beach",
    note: "Mellow, consistent beach break by the pier. Forgiving peaks — the go-to spot to learn on the Central Coast." },

  // ───────────── Santa Barbara / Ventura ─────────────
  { id: "surf-beach", name: "Surf Beach", region: "Lompoc, CA", lat: 34.677, lon: -120.602,
    facing: 260, idealSwellDir: 280, idealSize: [3, 8], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Exposed, swell-magnet beach break by the train tracks. Often windy; pure NW-swell exposure." },
  { id: "jalama", name: "Jalama Beach", region: "Lompoc, CA", lat: 34.512, lon: -120.500,
    facing: 250, idealSwellDir: 275, idealSize: [3, 10], idealTide: "mid", level: "advanced", type: "beach",
    note: "Remote, powerful peaks that catch every swell — but the wind is the catch. Reward for the committed." },
  { id: "campus-point", name: "Campus Point (UCSB)", region: "Goleta, CA", lat: 34.408, lon: -119.844,
    facing: 200, idealSwellDir: 220, idealSize: [2, 8], idealTide: "mid", level: "intermediate", type: "point",
    note: "Wrapping right point at UCSB; loves a S/SW swell and stays clean when W wind blows." },
  { id: "rincon", name: "Rincon", region: "Carpinteria, CA", lat: 34.373, lon: -119.476,
    facing: 230, idealSwellDir: 270, idealSize: [2, 10], idealTide: "mid", level: "intermediate", type: "point",
    note: "The Queen of the Coast — a long, peeling right point on a W/NW swell. Magic, and packed, when it's on." },
  { id: "sandspit", name: "Sandspit", region: "Santa Barbara, CA", lat: 34.404, lon: -119.690,
    facing: 210, idealSwellDir: 250, idealSize: [3, 10], idealTide: "low", level: "advanced", type: "reef",
    note: "Short, heavy, barreling right at the harbor mouth. Needs a big wrapping W swell and low tide." },
  { id: "cstreet", name: "C Street (Ventura Point)", region: "Ventura, CA", lat: 34.271, lon: -119.302,
    facing: 210, idealSwellDir: 250, idealSize: [2, 8], idealTide: "mid", level: "intermediate", type: "point",
    note: "Long cobblestone right point off the Ventura pier. Classic, mellow, and almost always crowded." },
  { id: "emma-wood", name: "Emma Wood", region: "Ventura, CA", lat: 34.285, lon: -119.330,
    facing: 220, idealSwellDir: 250, idealSize: [2, 8], idealTide: "mid", level: "intermediate", type: "point",
    note: "Cobblestone point/rivermouth that lines up on a solid W/NW swell. Rocky entry." },

  // ───────────── Los Angeles / Malibu / South Bay ─────────────
  { id: "zuma", name: "Zuma Beach", region: "Malibu, CA", lat: 34.020, lon: -118.821,
    facing: 200, idealSwellDir: 230, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Wide-open Malibu beach break with punchy peaks on a W/SW swell. Strong rips when it's big." },
  { id: "malibu", name: "Malibu (First Point)", region: "Malibu, CA", lat: 34.031, lon: -118.679,
    facing: 200, idealSwellDir: 195, idealSize: [2, 6], idealTide: "low", level: "intermediate", type: "point",
    note: "World-class peeling right point on a S/SW swell. Glassy mornings are magic; gets a circus when good." },
  { id: "topanga", name: "Topanga", region: "Malibu, CA", lat: 34.038, lon: -118.583,
    facing: 200, idealSwellDir: 220, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "point",
    note: "Right point/rivermouth on a S/SW swell, tucked into a rocky cove. Lines up nicely when it's working." },
  { id: "venice", name: "Venice Breakwater", region: "Venice, CA", lat: 33.978, lon: -118.475,
    facing: 250, idealSwellDir: 250, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Sheltered city beach break by the breakwater — a gritty LA staple that holds a bit of size." },
  { id: "el-porto", name: "El Porto", region: "Manhattan Beach, CA", lat: 33.902, lon: -118.421,
    facing: 250, idealSwellDir: 260, idealSize: [2, 8], idealTide: "mid", level: "intermediate", type: "beach",
    note: "The most consistent South Bay beach break; picks up swell from nearly every angle." },

  // ───────────── Orange County ─────────────
  { id: "bolsa-chica", name: "Bolsa Chica", region: "Huntington Beach, CA", lat: 33.690, lon: -118.045,
    facing: 215, idealSwellDir: 200, idealSize: [2, 6], idealTide: "mid", level: "beginner", type: "beach",
    note: "Long, forgiving beach break north of HB pier. Plenty of room and gentle peaks for learning." },
  { id: "huntington", name: "Huntington Beach", region: "Huntington Beach, CA", lat: 33.655, lon: -118.003,
    facing: 220, idealSwellDir: 200, idealSize: [2, 6], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Consistent SoCal beach break. Likes a combo S/SW swell. Morning glass before the onshore sea breeze." },
  { id: "the-wedge", name: "The Wedge", region: "Newport Beach, CA", lat: 33.593, lon: -117.882,
    facing: 200, idealSwellDir: 195, idealSize: [3, 15], idealTide: "mid", level: "advanced", type: "beach",
    note: "Freak shorebreak wedge by the jetty. Bone-crunching on a big S swell — bodysurf/boog experts only." },
  { id: "salt-creek", name: "Salt Creek", region: "Dana Point, CA", lat: 33.479, lon: -117.728,
    facing: 215, idealSwellDir: 200, idealSize: [2, 8], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Consistent OC beach/reef peaks below the bluff; works on both S and W swell." },
  { id: "doheny", name: "Doheny", region: "Dana Point, CA", lat: 33.461, lon: -117.686,
    facing: 200, idealSwellDir: 195, idealSize: [1, 5], idealTide: "mid", level: "beginner", type: "point",
    note: "Mellow, protected longboard wave — the South OC learner classic on a S swell." },
  { id: "trestles", name: "Lower Trestles", region: "San Clemente, CA", lat: 33.385, lon: -117.589,
    facing: 215, idealSwellDir: 200, idealSize: [2, 8], idealTide: "high", level: "advanced", type: "point",
    note: "High-performance cobblestone point. Rewards a clean SW swell. Light wind & rising tide are the sweet spot." },
  { id: "tstreet", name: "T-Street", region: "San Clemente, CA", lat: 33.412, lon: -117.611,
    facing: 215, idealSwellDir: 200, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Friendly San Clemente beach break that takes combo swells; an all-around fun, family spot." },

  // ───────────── San Diego County ─────────────
  { id: "oceanside", name: "Oceanside Pier", region: "Oceanside, CA", lat: 33.193, lon: -117.386,
    facing: 260, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Consistent North County beach break around the pier and harbor jetties. Works on most swells." },
  { id: "swamis", name: "Swami's", region: "Encinitas, CA", lat: 33.036, lon: -117.292,
    facing: 250, idealSwellDir: 270, idealSize: [2, 8], idealTide: "mid", level: "intermediate", type: "reef",
    note: "Long, classic right-hand reef point. Loves a W/NW swell and reels on the right tide." },
  { id: "cardiff", name: "Cardiff Reef", region: "Cardiff, CA", lat: 33.018, lon: -117.281,
    facing: 250, idealSwellDir: 270, idealSize: [2, 8], idealTide: "mid", level: "intermediate", type: "reef",
    note: "Mellow cobblestone reef — a longboard-friendly North County staple with a long rideable wave." },
  { id: "blacks", name: "Black's Beach", region: "La Jolla, CA", lat: 32.889, lon: -117.252,
    facing: 265, idealSwellDir: 280, idealSize: [3, 12], idealTide: "mid", level: "advanced", type: "beach",
    note: "Powerful, hollow beach break fed by an offshore canyon. Punchy and serious when the NW swell lights it up." },
  { id: "la-jolla-shores", name: "La Jolla Shores", region: "La Jolla, CA", lat: 32.857, lon: -117.257,
    facing: 250, idealSwellDir: 260, idealSize: [1, 6], idealTide: "mid", level: "beginner", type: "beach",
    note: "Gentle, sandy beach break in a protected bay — prime for beginners, schools and longboards." },
  { id: "windansea", name: "Windansea", region: "La Jolla, CA", lat: 32.828, lon: -117.281,
    facing: 250, idealSwellDir: 270, idealSize: [2, 10], idealTide: "low", level: "advanced", type: "reef",
    note: "Powerful, localized reef with shifting peaks. Best on a punchy W/NW swell at lower tides." },
  { id: "ob-sd", name: "Ocean Beach Pier (SD)", region: "San Diego, CA", lat: 32.749, lon: -117.253,
    facing: 260, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Reliable city beach break by the pier. Handles most swells; a dependable everyday wave." },
  { id: "sunset-cliffs", name: "Sunset Cliffs", region: "San Diego, CA", lat: 32.717, lon: -117.257,
    facing: 255, idealSwellDir: 275, idealSize: [2, 10], idealTide: "mid", level: "advanced", type: "reef",
    note: "Cliff-lined reef breaks that need some size to fire. Access and tide-sensitive; rocky." },
  { id: "imperial-beach", name: "Imperial Beach", region: "Imperial Beach, CA", lat: 32.579, lon: -117.135,
    facing: 250, idealSwellDir: 200, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "The southernmost CA beach break; picks up S swell especially well by the pier." },


  // ───────────── Added from the California directory ─────────────
  { id: "south-beach", name: "South Beach", region: "Crescent City, CA", lat: 41.739, lon: -124.201,
    facing: 250, idealSwellDir: 250, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "South Beach — a beach break near Crescent City, CA." },
  { id: "point-st-george", name: "Point St. George", region: "Crescent City, CA", lat: 41.789, lon: -124.255,
    facing: 270, idealSwellDir: 270, idealSize: [2, 9], idealTide: "mid", level: "advanced", type: "reef",
    note: "Point St. George — a reef break near Crescent City, CA." },
  { id: "wilson-creek", name: "Wilson Creek", region: "Klamath, CA", lat: 41.607, lon: -124.103,
    facing: 270, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Wilson Creek — a beach break near Klamath, CA." },
  { id: "moonstone-beach-trinidad", name: "Moonstone Beach (Trinidad)", region: "Trinidad, CA", lat: 41.021, lon: -124.112,
    facing: 265, idealSwellDir: 265, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Moonstone Beach (Trinidad) — a beach break near Trinidad, CA." },
  { id: "camel-rock", name: "Camel Rock", region: "Trinidad, CA", lat: 41.071, lon: -124.165,
    facing: 270, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Camel Rock — a beach break near Trinidad, CA." },
  { id: "samoa-beach", name: "Samoa Beach", region: "Samoa, CA", lat: 40.788, lon: -124.227,
    facing: 270, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "advanced", type: "beach",
    note: "Samoa Beach — a beach break near Samoa, CA." },
  { id: "north-jetty", name: "North Jetty", region: "Eureka, CA", lat: 40.766, lon: -124.235,
    facing: 270, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "advanced", type: "beach",
    note: "North Jetty — a beach break near Eureka, CA." },
  { id: "centerville-beach", name: "Centerville Beach", region: "Ferndale, CA", lat: 40.564, lon: -124.353,
    facing: 265, idealSwellDir: 265, idealSize: [2, 7], idealTide: "mid", level: "advanced", type: "beach",
    note: "Centerville Beach — a beach break near Ferndale, CA." },
  { id: "shelter-cove", name: "Shelter Cove", region: "Shelter Cove, CA", lat: 40.026, lon: -124.073,
    facing: 230, idealSwellDir: 230, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Shelter Cove — a beach break near Shelter Cove, CA." },
  { id: "westport", name: "Westport", region: "Westport, CA", lat: 39.636, lon: -123.783,
    facing: 270, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "advanced", type: "beach",
    note: "Westport — a beach break near Westport, CA." },
  { id: "virgin-creek", name: "Virgin Creek", region: "Fort Bragg, CA", lat: 39.466, lon: -123.802,
    facing: 270, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Virgin Creek — a beach break near Fort Bragg, CA." },
  { id: "pudding-creek", name: "Pudding Creek", region: "Fort Bragg, CA", lat: 39.458, lon: -123.808,
    facing: 270, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Pudding Creek — a beach break near Fort Bragg, CA." },
  { id: "caspar-beach", name: "Caspar Beach", region: "Caspar, CA", lat: 39.362, lon: -123.818,
    facing: 265, idealSwellDir: 265, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Caspar Beach — a beach break near Caspar, CA." },
  { id: "big-river", name: "Big River", region: "Mendocino, CA", lat: 39.301, lon: -123.793,
    facing: 260, idealSwellDir: 260, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Big River — a beach break near Mendocino, CA." },
  { id: "arena-cove", name: "Arena Cove", region: "Point Arena, CA", lat: 38.911, lon: -123.711,
    facing: 250, idealSwellDir: 250, idealSize: [2, 9], idealTide: "mid", level: "advanced", type: "reef",
    note: "Arena Cove — a reef break near Point Arena, CA." },
  { id: "manchester-state-beach", name: "Manchester State Beach", region: "Manchester, CA", lat: 38.968, lon: -123.692,
    facing: 270, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Manchester State Beach — a beach break near Manchester, CA." },
  { id: "gualala", name: "Gualala", region: "Gualala, CA", lat: 38.768, lon: -123.534,
    facing: 260, idealSwellDir: 260, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Gualala — a beach break near Gualala, CA." },
  { id: "salmon-creek", name: "Salmon Creek", region: "Bodega Bay, CA", lat: 38.352, lon: -123.067,
    facing: 270, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Salmon Creek — a beach break near Bodega Bay, CA." },
  { id: "doran-beach", name: "Doran Beach", region: "Bodega Bay, CA", lat: 38.309, lon: -123.034,
    facing: 200, idealSwellDir: 200, idealSize: [2, 7], idealTide: "mid", level: "beginner", type: "beach",
    note: "Doran Beach — a beach break near Bodega Bay, CA." },
  { id: "dillon-beach", name: "Dillon Beach", region: "Dillon Beach, CA", lat: 38.251, lon: -122.962,
    facing: 260, idealSwellDir: 260, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Dillon Beach — a beach break near Dillon Beach, CA." },
  { id: "stinson-beach", name: "Stinson Beach", region: "Stinson Beach, CA", lat: 37.901, lon: -122.642,
    facing: 250, idealSwellDir: 250, idealSize: [2, 7], idealTide: "mid", level: "beginner", type: "beach",
    note: "Stinson Beach — a beach break near Stinson Beach, CA." },
  { id: "rodeo-beach", name: "Rodeo Beach", region: "Sausalito, CA", lat: 37.832, lon: -122.54,
    facing: 250, idealSwellDir: 250, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Rodeo Beach — a beach break near Sausalito, CA." },
  { id: "kelly-s-cove", name: "Kelly's Cove", region: "San Francisco, CA", lat: 37.778, lon: -122.513,
    facing: 270, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "advanced", type: "beach",
    note: "Kelly's Cove — a beach break near San Francisco, CA." },
  { id: "fort-point", name: "Fort Point", region: "San Francisco, CA", lat: 37.81, lon: -122.477,
    facing: 250, idealSwellDir: 250, idealSize: [2, 9], idealTide: "mid", level: "advanced", type: "reef",
    note: "Fort Point — a reef break near San Francisco, CA." },
  { id: "rockaway-beach-pacifica", name: "Rockaway Beach (Pacifica)", region: "Pacifica, CA", lat: 37.61, lon: -122.493,
    facing: 270, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Rockaway Beach (Pacifica) — a beach break near Pacifica, CA." },
  { id: "sharp-park", name: "Sharp Park", region: "Pacifica, CA", lat: 37.632, lon: -122.494,
    facing: 270, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Sharp Park — a beach break near Pacifica, CA." },
  { id: "montara-state-beach", name: "Montara State Beach", region: "Montara, CA", lat: 37.552, lon: -122.514,
    facing: 270, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "advanced", type: "beach",
    note: "Montara State Beach — a beach break near Montara, CA." },
  { id: "gray-whale-cove", name: "Gray Whale Cove", region: "Montara, CA", lat: 37.563, lon: -122.518,
    facing: 270, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Gray Whale Cove — a beach break near Montara, CA." },
  { id: "pillar-point", name: "Pillar Point", region: "Half Moon Bay, CA", lat: 37.496, lon: -122.498,
    facing: 290, idealSwellDir: 290, idealSize: [2, 9], idealTide: "mid", level: "advanced", type: "reef",
    note: "Pillar Point — a reef break near Half Moon Bay, CA." },
  { id: "surfer-s-beach", name: "Surfer's Beach", region: "El Granada, CA", lat: 37.502, lon: -122.482,
    facing: 270, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "beginner", type: "beach",
    note: "Surfer's Beach — a beach break near El Granada, CA." },
  { id: "san-gregorio", name: "San Gregorio", region: "San Gregorio, CA", lat: 37.323, lon: -122.401,
    facing: 260, idealSwellDir: 260, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "San Gregorio — a beach break near San Gregorio, CA." },
  { id: "pescadero", name: "Pescadero", region: "Pescadero, CA", lat: 37.262, lon: -122.413,
    facing: 260, idealSwellDir: 260, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Pescadero — a beach break near Pescadero, CA." },
  { id: "waddell-creek", name: "Waddell Creek", region: "Davenport, CA", lat: 37.097, lon: -122.277,
    facing: 250, idealSwellDir: 250, idealSize: [2, 7], idealTide: "mid", level: "advanced", type: "beach",
    note: "Waddell Creek — a beach break near Davenport, CA." },
  { id: "scott-creek", name: "Scott Creek", region: "Davenport, CA", lat: 37.042, lon: -122.234,
    facing: 255, idealSwellDir: 255, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Scott Creek — a beach break near Davenport, CA." },
  { id: "davenport-landing", name: "Davenport Landing", region: "Davenport, CA", lat: 37.019, lon: -122.213,
    facing: 255, idealSwellDir: 255, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Davenport Landing — a beach break near Davenport, CA." },
  { id: "four-mile", name: "Four Mile", region: "Santa Cruz, CA", lat: 36.985, lon: -122.156,
    facing: 220, idealSwellDir: 220, idealSize: [2, 8], idealTide: "mid", level: "advanced", type: "point",
    note: "Four Mile — a point break near Santa Cruz, CA." },
  { id: "natural-bridges", name: "Natural Bridges", region: "Santa Cruz, CA", lat: 36.949, lon: -122.058,
    facing: 215, idealSwellDir: 215, idealSize: [2, 8], idealTide: "mid", level: "intermediate", type: "point",
    note: "Natural Bridges — a point break near Santa Cruz, CA." },
  { id: "mitchell-s-cove", name: "Mitchell's Cove", region: "Santa Cruz, CA", lat: 36.952, lon: -122.044,
    facing: 210, idealSwellDir: 210, idealSize: [2, 9], idealTide: "mid", level: "intermediate", type: "reef",
    note: "Mitchell's Cove — a reef break near Santa Cruz, CA." },
  { id: "38th-avenue", name: "38th Avenue", region: "Santa Cruz, CA", lat: 36.961, lon: -121.972,
    facing: 200, idealSwellDir: 200, idealSize: [2, 8], idealTide: "mid", level: "intermediate", type: "point",
    note: "38th Avenue — a point break near Santa Cruz, CA." },
  { id: "capitola", name: "Capitola", region: "Capitola, CA", lat: 36.971, lon: -121.951,
    facing: 195, idealSwellDir: 195, idealSize: [2, 7], idealTide: "mid", level: "beginner", type: "beach",
    note: "Capitola — a beach break near Capitola, CA." },
  { id: "manresa", name: "Manresa", region: "La Selva Beach, CA", lat: 36.934, lon: -121.851,
    facing: 200, idealSwellDir: 200, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Manresa — a beach break near La Selva Beach, CA." },
  { id: "rio-del-mar", name: "Rio Del Mar", region: "Aptos, CA", lat: 36.965, lon: -121.901,
    facing: 200, idealSwellDir: 200, idealSize: [2, 7], idealTide: "mid", level: "beginner", type: "beach",
    note: "Rio Del Mar — a beach break near Aptos, CA." },
  { id: "moss-landing", name: "Moss Landing", region: "Moss Landing, CA", lat: 36.802, lon: -121.789,
    facing: 270, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "advanced", type: "beach",
    note: "Moss Landing — a beach break near Moss Landing, CA." },
  { id: "marina-state-beach", name: "Marina State Beach", region: "Marina, CA", lat: 36.694, lon: -121.808,
    facing: 270, idealSwellDir: 270, idealSize: [2, 7], idealTide: "mid", level: "advanced", type: "beach",
    note: "Marina State Beach — a beach break near Marina, CA." },
  { id: "monastery-beach", name: "Monastery Beach", region: "Carmel, CA", lat: 36.522, lon: -121.923,
    facing: 250, idealSwellDir: 250, idealSize: [2, 7], idealTide: "mid", level: "advanced", type: "beach",
    note: "Monastery Beach — a beach break near Carmel, CA." },
  { id: "andrew-molera", name: "Andrew Molera", region: "Big Sur, CA", lat: 36.285, lon: -121.862,
    facing: 250, idealSwellDir: 250, idealSize: [2, 7], idealTide: "mid", level: "advanced", type: "beach",
    note: "Andrew Molera — a beach break near Big Sur, CA." },
  { id: "willow-creek", name: "Willow Creek", region: "Big Sur, CA", lat: 35.921, lon: -121.474,
    facing: 250, idealSwellDir: 250, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Willow Creek — a beach break near Big Sur, CA." },
  { id: "san-simeon", name: "San Simeon", region: "San Simeon, CA", lat: 35.643, lon: -121.189,
    facing: 260, idealSwellDir: 260, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "San Simeon — a beach break near San Simeon, CA." },
  { id: "pico-creek", name: "Pico Creek", region: "San Simeon, CA", lat: 35.617, lon: -121.14,
    facing: 265, idealSwellDir: 265, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Pico Creek — a beach break near San Simeon, CA." },
  { id: "studio-drive", name: "Studio Drive", region: "Cayucos, CA", lat: 35.453, lon: -120.909,
    facing: 285, idealSwellDir: 285, idealSize: [2, 7], idealTide: "mid", level: "beginner", type: "beach",
    note: "Studio Drive — a beach break near Cayucos, CA." },
  { id: "morro-strand", name: "Morro Strand", region: "Morro Bay, CA", lat: 35.4, lon: -120.868,
    facing: 275, idealSwellDir: 275, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Morro Strand — a beach break near Morro Bay, CA." },
  { id: "the-pit", name: "The Pit", region: "Morro Bay, CA", lat: 35.37, lon: -120.866,
    facing: 275, idealSwellDir: 275, idealSize: [2, 7], idealTide: "mid", level: "advanced", type: "beach",
    note: "The Pit — a beach break near Morro Bay, CA." },
  { id: "oceano", name: "Oceano", region: "Oceano, CA", lat: 35.099, lon: -120.633,
    facing: 250, idealSwellDir: 250, idealSize: [2, 7], idealTide: "mid", level: "beginner", type: "beach",
    note: "Oceano — a beach break near Oceano, CA." },
  { id: "ocean-beach-park", name: "Ocean Beach Park", region: "Lompoc, CA", lat: 34.69, lon: -120.602,
    facing: 255, idealSwellDir: 255, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Ocean Beach Park — a beach break near Lompoc, CA." },
  { id: "sands-coal-oil-point", name: "Sands (Coal Oil Point)", region: "Goleta, CA", lat: 34.406, lon: -119.878,
    facing: 200, idealSwellDir: 200, idealSize: [2, 8], idealTide: "mid", level: "intermediate", type: "point",
    note: "Sands (Coal Oil Point) — a point break near Goleta, CA." },
  { id: "devereux", name: "Devereux", region: "Goleta, CA", lat: 34.412, lon: -119.873,
    facing: 195, idealSwellDir: 195, idealSize: [2, 9], idealTide: "mid", level: "intermediate", type: "reef",
    note: "Devereux — a reef break near Goleta, CA." },
  { id: "leadbetter", name: "Leadbetter", region: "Santa Barbara, CA", lat: 34.404, lon: -119.692,
    facing: 200, idealSwellDir: 200, idealSize: [2, 8], idealTide: "mid", level: "beginner", type: "point",
    note: "Leadbetter — a point break near Santa Barbara, CA." },
  { id: "hammond-s", name: "Hammond's", region: "Montecito, CA", lat: 34.42, lon: -119.624,
    facing: 195, idealSwellDir: 195, idealSize: [2, 9], idealTide: "mid", level: "intermediate", type: "reef",
    note: "Hammond's — a reef break near Montecito, CA." },
  { id: "carpinteria-state-beach", name: "Carpinteria State Beach", region: "Carpinteria, CA", lat: 34.389, lon: -119.519,
    facing: 200, idealSwellDir: 200, idealSize: [2, 7], idealTide: "mid", level: "beginner", type: "beach",
    note: "Carpinteria State Beach — a beach break near Carpinteria, CA." },
  { id: "mussel-shoals", name: "Mussel Shoals", region: "Ventura, CA", lat: 34.359, lon: -119.443,
    facing: 195, idealSwellDir: 195, idealSize: [2, 8], idealTide: "mid", level: "intermediate", type: "point",
    note: "Mussel Shoals — a point break near Ventura, CA." },
  { id: "hobson", name: "Hobson", region: "Ventura, CA", lat: 34.357, lon: -119.43,
    facing: 195, idealSwellDir: 195, idealSize: [2, 9], idealTide: "mid", level: "intermediate", type: "reef",
    note: "Hobson — a reef break near Ventura, CA." },
  { id: "faria", name: "Faria", region: "Ventura, CA", lat: 34.334, lon: -119.408,
    facing: 195, idealSwellDir: 195, idealSize: [2, 9], idealTide: "mid", level: "intermediate", type: "reef",
    note: "Faria — a reef break near Ventura, CA." },
  { id: "pitas-point", name: "Pitas Point", region: "Ventura, CA", lat: 34.343, lon: -119.443,
    facing: 200, idealSwellDir: 200, idealSize: [2, 8], idealTide: "mid", level: "intermediate", type: "point",
    note: "Pitas Point — a point break near Ventura, CA." },
  { id: "mondos", name: "Mondos", region: "Ventura, CA", lat: 34.349, lon: -119.441,
    facing: 200, idealSwellDir: 200, idealSize: [2, 8], idealTide: "mid", level: "beginner", type: "point",
    note: "Mondos — a point break near Ventura, CA." },
  { id: "pierpont", name: "Pierpont", region: "Ventura, CA", lat: 34.262, lon: -119.292,
    facing: 210, idealSwellDir: 210, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Pierpont — a beach break near Ventura, CA." },
  { id: "ventura-harbor", name: "Ventura Harbor", region: "Ventura, CA", lat: 34.244, lon: -119.268,
    facing: 215, idealSwellDir: 215, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Ventura Harbor — a beach break near Ventura, CA." },
  { id: "silver-strand", name: "Silver Strand", region: "Oxnard, CA", lat: 34.169, lon: -119.231,
    facing: 230, idealSwellDir: 230, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Silver Strand — a beach break near Oxnard, CA." },
  { id: "hollywood-beach", name: "Hollywood Beach", region: "Oxnard, CA", lat: 34.162, lon: -119.228,
    facing: 235, idealSwellDir: 235, idealSize: [2, 7], idealTide: "mid", level: "beginner", type: "beach",
    note: "Hollywood Beach — a beach break near Oxnard, CA." },
  { id: "mandalay", name: "Mandalay", region: "Oxnard, CA", lat: 34.199, lon: -119.252,
    facing: 245, idealSwellDir: 245, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Mandalay — a beach break near Oxnard, CA." },
  { id: "oxnard-shores", name: "Oxnard Shores", region: "Oxnard, CA", lat: 34.192, lon: -119.249,
    facing: 245, idealSwellDir: 245, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Oxnard Shores — a beach break near Oxnard, CA." },
  { id: "county-line", name: "County Line", region: "Malibu, CA", lat: 34.05, lon: -118.963,
    facing: 210, idealSwellDir: 210, idealSize: [2, 8], idealTide: "mid", level: "intermediate", type: "point",
    note: "County Line — a point break near Malibu, CA." },
  { id: "leo-carrillo", name: "Leo Carrillo", region: "Malibu, CA", lat: 34.044, lon: -118.936,
    facing: 205, idealSwellDir: 205, idealSize: [2, 9], idealTide: "mid", level: "intermediate", type: "reef",
    note: "Leo Carrillo — a reef break near Malibu, CA." },
  { id: "nicholas-canyon", name: "Nicholas Canyon", region: "Malibu, CA", lat: 34.041, lon: -118.927,
    facing: 205, idealSwellDir: 205, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Nicholas Canyon — a beach break near Malibu, CA." },
  { id: "point-dume", name: "Point Dume", region: "Malibu, CA", lat: 34.001, lon: -118.806,
    facing: 200, idealSwellDir: 200, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Point Dume — a beach break near Malibu, CA." },
  { id: "latigo", name: "Latigo", region: "Malibu, CA", lat: 34.038, lon: -118.741,
    facing: 200, idealSwellDir: 200, idealSize: [2, 8], idealTide: "mid", level: "intermediate", type: "point",
    note: "Latigo — a point break near Malibu, CA." },
  { id: "sunset-santa-monica", name: "Sunset (Santa Monica)", region: "Pacific Palisades, CA", lat: 34.039, lon: -118.561,
    facing: 200, idealSwellDir: 200, idealSize: [2, 8], idealTide: "mid", level: "beginner", type: "point",
    note: "Sunset (Santa Monica) — a point break near Pacific Palisades, CA." },
  { id: "bay-street", name: "Bay Street", region: "Santa Monica, CA", lat: 34.009, lon: -118.494,
    facing: 230, idealSwellDir: 230, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Bay Street — a beach break near Santa Monica, CA." },
  { id: "manhattan-beach", name: "Manhattan Beach", region: "Manhattan Beach, CA", lat: 33.889, lon: -118.418,
    facing: 250, idealSwellDir: 250, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Manhattan Beach — a beach break near Manhattan Beach, CA." },
  { id: "hermosa-beach", name: "Hermosa Beach", region: "Hermosa Beach, CA", lat: 33.862, lon: -118.404,
    facing: 250, idealSwellDir: 250, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Hermosa Beach — a beach break near Hermosa Beach, CA." },
  { id: "redondo-breakwater", name: "Redondo Breakwater", region: "Redondo Beach, CA", lat: 33.841, lon: -118.394,
    facing: 245, idealSwellDir: 245, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Redondo Breakwater — a beach break near Redondo Beach, CA." },
  { id: "torrance-beach", name: "Torrance Beach", region: "Torrance, CA", lat: 33.813, lon: -118.391,
    facing: 245, idealSwellDir: 245, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Torrance Beach — a beach break near Torrance, CA." },
  { id: "haggerty-s", name: "Haggerty's", region: "Palos Verdes, CA", lat: 33.802, lon: -118.392,
    facing: 230, idealSwellDir: 230, idealSize: [2, 9], idealTide: "mid", level: "advanced", type: "reef",
    note: "Haggerty's — a reef break near Palos Verdes, CA." },
  { id: "lunada-bay", name: "Lunada Bay", region: "Palos Verdes, CA", lat: 33.772, lon: -118.425,
    facing: 290, idealSwellDir: 290, idealSize: [2, 9], idealTide: "mid", level: "advanced", type: "reef",
    note: "Lunada Bay — a reef break near Palos Verdes, CA." },
  { id: "bluff-cove", name: "Bluff Cove", region: "Palos Verdes, CA", lat: 33.781, lon: -118.412,
    facing: 270, idealSwellDir: 270, idealSize: [2, 9], idealTide: "mid", level: "advanced", type: "reef",
    note: "Bluff Cove — a reef break near Palos Verdes, CA." },
  { id: "seal-beach", name: "Seal Beach", region: "Seal Beach, CA", lat: 33.74, lon: -118.104,
    facing: 215, idealSwellDir: 215, idealSize: [2, 7], idealTide: "mid", level: "beginner", type: "beach",
    note: "Seal Beach — a beach break near Seal Beach, CA." },
  { id: "river-jetties", name: "River Jetties", region: "Newport Beach, CA", lat: 33.631, lon: -117.959,
    facing: 210, idealSwellDir: 210, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "River Jetties — a beach break near Newport Beach, CA." },
  { id: "blackies", name: "Blackies", region: "Newport Beach, CA", lat: 33.608, lon: -117.93,
    facing: 210, idealSwellDir: 210, idealSize: [2, 7], idealTide: "mid", level: "beginner", type: "beach",
    note: "Blackies — a beach break near Newport Beach, CA." },
  { id: "newport-point", name: "Newport Point", region: "Newport Beach, CA", lat: 33.592, lon: -117.879,
    facing: 200, idealSwellDir: 200, idealSize: [2, 7], idealTide: "mid", level: "advanced", type: "beach",
    note: "Newport Point — a beach break near Newport Beach, CA." },
  { id: "crystal-cove", name: "Crystal Cove", region: "Newport Beach, CA", lat: 33.568, lon: -117.834,
    facing: 210, idealSwellDir: 210, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Crystal Cove — a beach break near Newport Beach, CA." },
  { id: "brooks-street", name: "Brooks Street", region: "Laguna Beach, CA", lat: 33.537, lon: -117.787,
    facing: 210, idealSwellDir: 210, idealSize: [2, 9], idealTide: "mid", level: "advanced", type: "reef",
    note: "Brooks Street — a reef break near Laguna Beach, CA." },
  { id: "thalia-street", name: "Thalia Street", region: "Laguna Beach, CA", lat: 33.541, lon: -117.789,
    facing: 210, idealSwellDir: 210, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Thalia Street — a beach break near Laguna Beach, CA." },
  { id: "aliso-beach", name: "Aliso Beach", region: "Laguna Beach, CA", lat: 33.51, lon: -117.752,
    facing: 210, idealSwellDir: 210, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Aliso Beach — a beach break near Laguna Beach, CA." },
  { id: "strands", name: "Strands", region: "Dana Point, CA", lat: 33.471, lon: -117.713,
    facing: 215, idealSwellDir: 215, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Strands — a beach break near Dana Point, CA." },
  { id: "san-onofre", name: "San Onofre", region: "San Clemente, CA", lat: 33.38, lon: -117.567,
    facing: 215, idealSwellDir: 215, idealSize: [2, 8], idealTide: "mid", level: "beginner", type: "point",
    note: "San Onofre — a point break near San Clemente, CA." },
  { id: "uppers", name: "Uppers", region: "San Clemente, CA", lat: 33.391, lon: -117.593,
    facing: 210, idealSwellDir: 210, idealSize: [2, 8], idealTide: "mid", level: "advanced", type: "point",
    note: "Uppers — a point break near San Clemente, CA." },
  { id: "cottons", name: "Cottons", region: "San Clemente, CA", lat: 33.398, lon: -117.595,
    facing: 210, idealSwellDir: 210, idealSize: [2, 8], idealTide: "mid", level: "advanced", type: "point",
    note: "Cottons — a point break near San Clemente, CA." },
  { id: "churches", name: "Churches", region: "San Clemente, CA", lat: 33.372, lon: -117.567,
    facing: 215, idealSwellDir: 215, idealSize: [2, 8], idealTide: "mid", level: "intermediate", type: "point",
    note: "Churches — a point break near San Clemente, CA." },
  { id: "san-clemente-pier", name: "San Clemente Pier", region: "San Clemente, CA", lat: 33.418, lon: -117.622,
    facing: 215, idealSwellDir: 215, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "San Clemente Pier — a beach break near San Clemente, CA." },
  { id: "oceanside-harbor", name: "Oceanside Harbor", region: "Oceanside, CA", lat: 33.211, lon: -117.401,
    facing: 260, idealSwellDir: 260, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Oceanside Harbor — a beach break near Oceanside, CA." },
  { id: "tamarack", name: "Tamarack", region: "Carlsbad, CA", lat: 33.142, lon: -117.342,
    facing: 260, idealSwellDir: 260, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Tamarack — a beach break near Carlsbad, CA." },
  { id: "ponto", name: "Ponto", region: "Carlsbad, CA", lat: 33.082, lon: -117.313,
    facing: 255, idealSwellDir: 255, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Ponto — a beach break near Carlsbad, CA." },
  { id: "grandview", name: "Grandview", region: "Encinitas, CA", lat: 33.069, lon: -117.31,
    facing: 255, idealSwellDir: 255, idealSize: [2, 9], idealTide: "mid", level: "intermediate", type: "reef",
    note: "Grandview — a reef break near Encinitas, CA." },
  { id: "beacons", name: "Beacons", region: "Encinitas, CA", lat: 33.06, lon: -117.305,
    facing: 255, idealSwellDir: 255, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Beacons — a beach break near Encinitas, CA." },
  { id: "moonlight", name: "Moonlight", region: "Encinitas, CA", lat: 33.044, lon: -117.297,
    facing: 255, idealSwellDir: 255, idealSize: [2, 7], idealTide: "mid", level: "beginner", type: "beach",
    note: "Moonlight — a beach break near Encinitas, CA." },
  { id: "d-street", name: "D Street", region: "Encinitas, CA", lat: 33.04, lon: -117.296,
    facing: 255, idealSwellDir: 255, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "D Street — a beach break near Encinitas, CA." },
  { id: "pipes", name: "Pipes", region: "Encinitas, CA", lat: 33.024, lon: -117.288,
    facing: 255, idealSwellDir: 255, idealSize: [2, 9], idealTide: "mid", level: "intermediate", type: "reef",
    note: "Pipes — a reef break near Encinitas, CA." },
  { id: "seaside-reef", name: "Seaside Reef", region: "Cardiff, CA", lat: 33.012, lon: -117.284,
    facing: 255, idealSwellDir: 255, idealSize: [2, 9], idealTide: "mid", level: "intermediate", type: "reef",
    note: "Seaside Reef — a reef break near Cardiff, CA." },
  { id: "del-mar", name: "Del Mar", region: "Del Mar, CA", lat: 32.961, lon: -117.267,
    facing: 255, idealSwellDir: 255, idealSize: [2, 7], idealTide: "mid", level: "beginner", type: "beach",
    note: "Del Mar — a beach break near Del Mar, CA." },
  { id: "torrey-pines", name: "Torrey Pines", region: "Del Mar, CA", lat: 32.929, lon: -117.26,
    facing: 260, idealSwellDir: 260, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Torrey Pines — a beach break near Del Mar, CA." },
  { id: "scripps-pier", name: "Scripps Pier", region: "La Jolla, CA", lat: 32.866, lon: -117.254,
    facing: 260, idealSwellDir: 260, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Scripps Pier — a beach break near La Jolla, CA." },
  { id: "bird-rock", name: "Bird Rock", region: "La Jolla, CA", lat: 32.813, lon: -117.272,
    facing: 255, idealSwellDir: 255, idealSize: [2, 9], idealTide: "mid", level: "advanced", type: "reef",
    note: "Bird Rock — a reef break near La Jolla, CA." },
  { id: "tourmaline", name: "Tourmaline", region: "Pacific Beach, CA", lat: 32.802, lon: -117.26,
    facing: 260, idealSwellDir: 260, idealSize: [2, 9], idealTide: "mid", level: "beginner", type: "reef",
    note: "Tourmaline — a reef break near Pacific Beach, CA." },
  { id: "crystal-pier", name: "Crystal Pier", region: "Pacific Beach, CA", lat: 32.795, lon: -117.257,
    facing: 260, idealSwellDir: 260, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Crystal Pier — a beach break near Pacific Beach, CA." },
  { id: "mission-beach", name: "Mission Beach", region: "San Diego, CA", lat: 32.771, lon: -117.252,
    facing: 260, idealSwellDir: 260, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "Mission Beach — a beach break near San Diego, CA." },
  { id: "coronado", name: "Coronado", region: "Coronado, CA", lat: 32.681, lon: -117.19,
    facing: 255, idealSwellDir: 255, idealSize: [2, 7], idealTide: "mid", level: "beginner", type: "beach",
    note: "Coronado — a beach break near Coronado, CA." },
  { id: "tijuana-sloughs", name: "Tijuana Sloughs", region: "Imperial Beach, CA", lat: 32.549, lon: -117.131,
    facing: 255, idealSwellDir: 255, idealSize: [2, 7], idealTide: "mid", level: "advanced", type: "beach",
    note: "Tijuana Sloughs — a beach break near Imperial Beach, CA." },
  // ───────────── Marquee out-of-state ─────────────
  { id: "rockaway", name: "Rockaway Beach", region: "Queens, NY", lat: 40.583, lon: -73.815,
    facing: 160, idealSwellDir: 160, idealSize: [2, 7], idealTide: "mid", level: "intermediate", type: "beach",
    note: "East Coast beach break, best on a S/SE groundswell. NW wind grooms it. Hurricane season is prime." },
  { id: "pipeline", name: "Pipeline (Banzai)", region: "Oahu, HI", lat: 21.665, lon: -158.053,
    facing: 315, idealSwellDir: 315, idealSize: [4, 15], idealTide: "mid", level: "advanced", type: "reef",
    note: "Pro-only heavy reef barrel on NW swell. Shallow lava reef. Not a maybe-I'll-give-it-a-go wave." }
];

function getSpot(id) {
  return SPOTS.find(s => s.id === id);
}
